# assignments/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router and register our viewsets with it
router = DefaultRouter()
router.register(r'categories', views.AssignmentCategoryViewSet, basename='assignmentcategory')
router.register(r'grade-scales', views.AssignmentGradeScaleViewSet, basename='assignmentscalescale')
router.register(r'assignments', views.AssignmentViewSet, basename='assignment')
router.register(r'student-assignments', views.StudentAssignmentViewSet, basename='studentassignment')
router.register(r'groups', views.AssignmentGroupViewSet, basename='assignmentgroup')
router.register(r'group-memberships', views.GroupMembershipViewSet, basename='groupmembership')
router.register(r'comments', views.AssignmentCommentViewSet, basename='assignmentcomment')

urlpatterns = [
    # API routes from router
    path('', include(router.urls)),
    
    # ==================== DASHBOARD & ANALYTICS ====================
    path('dashboard/', views.assignment_dashboard, name='assignment-dashboard'),
    path('teacher-stats/', views.teacher_assignment_stats, name='teacher-assignment-stats'),
    path('student-progress/', views.student_progress_report, name='student-progress-all'),
    path('student-progress/<uuid:student_id>/', views.student_progress_report, name='student-progress'),
    
    # ==================== BULK OPERATIONS ====================
    path('assignments/bulk-create/', views.AssignmentViewSet.as_view({'post': 'bulk_create'}), name='bulk-create-assignments'),
    path('assignments/bulk-update/', views.AssignmentViewSet.as_view({'post': 'bulk_update'}), name='bulk-update-assignments'),
    path('student-assignments/bulk-grade/', views.StudentAssignmentViewSet.as_view({'post': 'bulk_grade'}), name='bulk-grade-assignments'),
    path('student-assignments/import-grades/', views.StudentAssignmentViewSet.as_view({'post': 'import_grades'}), name='import-grades'),
    
    # ==================== EXPORT ====================
    path('assignments/export/', views.AssignmentViewSet.as_view({'get': 'export'}), name='export-assignments'),
    path('student-assignments/export-grades/', views.StudentAssignmentViewSet.as_view({'get': 'export_grades'}), name='export-grades'),
    
    # ==================== CUSTOM ENDPOINTS ====================
    
    # Assignment endpoints
    path('assignments/upcoming/', views.AssignmentViewSet.as_view({'get': 'upcoming'}), name='upcoming-assignments'),
    path('assignments/overdue/', views.AssignmentViewSet.as_view({'get': 'overdue'}), name='overdue-assignments'),
    path('assignments/notifications/', views.AssignmentViewSet.as_view({'get': 'notifications'}), name='assignment-notifications'),
    path('assignments/my-assignments/', views.AssignmentViewSet.as_view({'get': 'my_assignments'}), name='my-assignments'),
    
    # Student assignment endpoints
    path('student-assignments/pending-grading/', views.StudentAssignmentViewSet.as_view({'get': 'pending_grading'}), name='pending-grading'),
    path('student-assignments/my-submissions/', views.StudentAssignmentViewSet.as_view({'get': 'my_submissions'}), name='my-submissions'),
    path('student-assignments/by-assignment/', views.StudentAssignmentViewSet.as_view({'get': 'by_assignment'}), name='student-assignments-by-assignment'),
    path('student-assignments/by-student/', views.StudentAssignmentViewSet.as_view({'get': 'by_student'}), name='student-assignments-by-student'),
    path('student-assignments/by-status/', views.StudentAssignmentViewSet.as_view({'get': 'by_status'}), name='student-assignments-by-status'),
    path('student-assignments/late-submissions/', views.StudentAssignmentViewSet.as_view({'get': 'late_submissions'}), name='late-submissions'),
    
    # ==================== ACTION ENDPOINTS ====================
    
    # These are automatically included by DRF router, but here are the explicit paths for reference:
    # Assignment actions (auto-generated by router but can be accessed as):
    # /api/v1/assignments/assignments/{id}/publish/
    # /api/v1/assignments/assignments/{id}/unpublish/
    # /api/v1/assignments/assignments/{id}/close/
    # /api/v1/assignments/assignments/{id}/duplicate/
    # /api/v1/assignments/assignments/{id}/stats/
    # /api/v1/assignments/assignments/{id}/submissions/
    # /api/v1/assignments/assignments/{id}/analytics/
    # /api/v1/assignments/assignments/{id}/comments/
    # /api/v1/assignments/assignments/{id}/upload-attachment/
    
    # Student assignment actions (auto-generated by router but can be accessed as):
    # /api/v1/assignments/student-assignments/{id}/submit/
    # /api/v1/assignments/student-assignments/{id}/grade/
    # /api/v1/assignments/student-assignments/{id}/allow-resubmission/
    # /api/v1/assignments/student-assignments/{id}/return-for-revision/
    # /api/v1/assignments/student-assignments/{id}/submission-history/
    # /api/v1/assignments/student-assignments/{id}/upload-attachment/
]

# ==================== URL PATTERN SUMMARY ====================
"""
This URLs file creates the following endpoints:

BASIC CRUD ENDPOINTS:
GET     /api/v1/assignments/categories/                    - List all categories
POST    /api/v1/assignments/categories/                    - Create new category
GET     /api/v1/assignments/categories/{id}/              - Get category details
PUT     /api/v1/assignments/categories/{id}/              - Update category
DELETE  /api/v1/assignments/categories/{id}/              - Delete category

GET     /api/v1/assignments/grade-scales/                  - List all grade scales
POST    /api/v1/assignments/grade-scales/                  - Create new grade scale
GET     /api/v1/assignments/grade-scales/{id}/            - Get grade scale details
PUT     /api/v1/assignments/grade-scales/{id}/            - Update grade scale
DELETE  /api/v1/assignments/grade-scales/{id}/            - Delete grade scale

GET     /api/v1/assignments/assignments/                   - List all assignments
POST    /api/v1/assignments/assignments/                   - Create new assignment
GET     /api/v1/assignments/assignments/{id}/             - Get assignment details
PUT     /api/v1/assignments/assignments/{id}/             - Update assignment
DELETE  /api/v1/assignments/assignments/{id}/             - Delete assignment

GET     /api/v1/assignments/student-assignments/           - List all student assignments
POST    /api/v1/assignments/student-assignments/           - Create student assignment
GET     /api/v1/assignments/student-assignments/{id}/     - Get student assignment details
PUT     /api/v1/assignments/student-assignments/{id}/     - Update student assignment
DELETE  /api/v1/assignments/student-assignments/{id}/     - Delete student assignment

ASSIGNMENT CUSTOM ACTIONS:
POST    /api/v1/assignments/assignments/{id}/publish/     - Publish assignment
POST    /api/v1/assignments/assignments/{id}/unpublish/   - Unpublish assignment
POST    /api/v1/assignments/assignments/{id}/close/       - Close assignment
POST    /api/v1/assignments/assignments/{id}/duplicate/   - Duplicate assignment
GET     /api/v1/assignments/assignments/{id}/stats/       - Get assignment statistics
GET     /api/v1/assignments/assignments/{id}/submissions/ - Get all submissions
GET     /api/v1/assignments/assignments/{id}/analytics/   - Get analytics
GET     /api/v1/assignments/assignments/{id}/comments/    - Get comments
POST    /api/v1/assignments/assignments/{id}/upload-attachment/ - Upload attachment

STUDENT ASSIGNMENT CUSTOM ACTIONS:
POST    /api/v1/assignments/student-assignments/{id}/submit/              - Submit assignment
POST    /api/v1/assignments/student-assignments/{id}/grade/               - Grade assignment
POST    /api/v1/assignments/student-assignments/{id}/allow-resubmission/  - Allow resubmission
POST    /api/v1/assignments/student-assignments/{id}/return-for-revision/ - Return for revision
GET     /api/v1/assignments/student-assignments/{id}/submission-history/  - Get submission history
POST    /api/v1/assignments/student-assignments/{id}/upload-attachment/   - Upload submission attachment

COLLECTION ENDPOINTS:
GET     /api/v1/assignments/assignments/upcoming/          - Get upcoming assignments
GET     /api/v1/assignments/assignments/overdue/           - Get overdue assignments
GET     /api/v1/assignments/assignments/notifications/     - Get notifications
GET     /api/v1/assignments/assignments/my-assignments/    - Get user's assignments
GET     /api/v1/assignments/dashboard/                     - Get dashboard data
GET     /api/v1/assignments/teacher-stats/                 - Get teacher statistics
GET     /api/v1/assignments/student-progress/              - Get student progress (all)
GET     /api/v1/assignments/student-progress/{student_id}/ - Get specific student progress

BULK OPERATIONS:
POST    /api/v1/assignments/assignments/bulk-create/       - Bulk create assignments
POST    /api/v1/assignments/assignments/bulk-update/       - Bulk update assignments
POST    /api/v1/assignments/student-assignments/bulk-grade/- Bulk grade assignments
POST    /api/v1/assignments/student-assignments/import-grades/ - Import grades from CSV

EXPORT ENDPOINTS:
GET     /api/v1/assignments/assignments/export/            - Export assignments (CSV)
GET     /api/v1/assignments/student-assignments/export-grades/ - Export grades (CSV)

FILTER ENDPOINTS:
GET     /api/v1/assignments/student-assignments/pending-grading/   - Get pending grading
GET     /api/v1/assignments/student-assignments/my-submissions/    - Get user's submissions
GET     /api/v1/assignments/student-assignments/by-assignment/     - Get by assignment ID
GET     /api/v1/assignments/student-assignments/by-student/        - Get by student ID
GET     /api/v1/assignments/student-assignments/by-status/         - Get by status
GET     /api/v1/assignments/student-assignments/late-submissions/  - Get late submissions

GROUPS AND COMMENTS:
GET     /api/v1/assignments/groups/                        - List all groups
POST    /api/v1/assignments/groups/                        - Create group
GET     /api/v1/assignments/groups/{id}/                  - Get group details
PUT     /api/v1/assignments/groups/{id}/                  - Update group
DELETE  /api/v1/assignments/groups/{id}/                  - Delete group

GET     /api/v1/assignments/group-memberships/             - List all memberships
POST    /api/v1/assignments/group-memberships/             - Create membership
GET     /api/v1/assignments/group-memberships/{id}/       - Get membership details
PUT     /api/v1/assignments/group-memberships/{id}/       - Update membership
DELETE  /api/v1/assignments/group-memberships/{id}/       - Delete membership

GET     /api/v1/assignments/comments/                      - List all comments
POST    /api/v1/assignments/comments/                      - Create comment
GET     /api/v1/assignments/comments/{id}/                - Get comment details
PUT     /api/v1/assignments/comments/{id}/                - Update comment
DELETE  /api/v1/assignments/comments/{id}/                - Delete comment
"""